name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, ast
          coverage: none

      - name: Coding Standard
        run: make test-php-style
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: Phan
        run: make test-php-phan

      - name: PHPStan
        run: make test-php-phpstan

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, xdebug
          coverage: xdebug
      - name: Run unit tests
        run: make test-php-unit

      - name: Upload coverage artifact
        if: matrix.php-versions == '7.4'
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: tests/output/clover.xml
        continue-on-error: true

  sonar-analysis:
    runs-on: ubuntu-latest
    needs: [tests]
    if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage-report
          path: tests/output
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true
